### PR TITLE
Deprecated JavaFX method fix

### PR DESCRIPTION
**Pull request by Jugen**

### CODE REVIEW

**Comment by Jugen** [comment]
We need to compile against Java 9 to resolve the deprecation warning ....

**Comment by trzimar** [comment]
Hi @Jugen, so this PR breaks Java 8 compatibility, right?

**Comment by Jugen** [comment]
Unfortunately yes, sorry.

**Comment by trzimar** [comment]
It might be worth mentioning in README.md. I've hit the compatibility issue when using [RichTextFX](https://github.com/FXMisc/RichTextFX) 0.10.7 that depends on Flowless 0.6.7

**Comment by Jugen** [comment]
Okay, have updated the README.md  and release descriptions. Thanks :-)

**Pull request merged**
